### PR TITLE
Add support for BRM schema changes

### PR DESCRIPTION
**Pull request by jtracey93**
## PR Summary

Add support for BRM schema changes as per https://github.com/Azure/bicep/issues/10810

Metadata usage changes for Bicep Module Registry

- `summary` will become `description` to align with OCI registry (short summary/overview)
- `description` (old) will become `details` (longer blurbs)

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**

### CODE REVIEW

**Comment by jtracey93** [comment]
@BernieWhite any thoughts on this one?

**Review by BernieWhite — CHANGES_REQUESTED** [review]
Thanks for the contribution @jtracey93. Sorry this has taken a while to get to.

Mostly looks good, but double check my comments below. Otherwise all good to merge.

Also, I added some tests so we don't accidentally break this in the future. Double check you are ok this these.

**Comment by jtracey93** [comment]
@BernieWhite LGTM

**Review by BernieWhite — APPROVED** [review]
Thanks @jtracey93 . All good to merge.

**Pull request merged**
